### ISSUE TITLE
not all Manufacturers show up on Region overview page.

### ISSUE THREAD

**Issue by JessicaGuy** [fablabbcn/makeworks#58]
Several newly added manufacturers don't show up on the Region page. 

For example Catalonia is missing several listed manufacturers 
https://make.works/regions/8

For example manufacturer Crea-re is missing https://make.works/companies/crea-re-studio
Her address shows up on her own listing page but not on the general Make Works Catalonia page

**Comment by benyscott** [comment]
At the bottom of the page where it says "Region updates", it's only the last 4 Companies added to that Region.

Just above the map, you can it says "Listings" and "Manufacturers in region: 10" and a link to all the manufacturers.

Do you mean you want to see all the manufacturers / companies for that region at the bottom of the page, rather than just the last 4?

**Comment by benyscott** [comment]
Yes, it seems Crea-re <https://make.works/companies/crea-re-studio> has the same address as Walter Montivero <https://make.works/companies/walter-montivero>W <https://make.works/companies/walter-montivero>alter Montivero, and Leonel Signs <https://make.works/companies/leonel-signs> and Penny P. Bags <https://make.works/companies/penny-p-bags> too..

I guess a little circle that shows the number of pins that are close to each like on the SmartCitizen website could be a solution.

**Comment by benyscott** [comment]
Now if two companies have the same address or are close to each other, they will be represented by a coloured circle with a number inside. If you click the cicle, you see the companies individually.

<img width="475" alt="Screenshot 2023-01-20 at 19 36 34" src="https://user-images.githubusercontent.com/4509663/213779386-40a815d5-e888-4d22-b399-d7db517f9167.png">
